version: '3.6'
services:
        # python: 
        #     build: .
        #     volumes:
        #         - ./ ./
        adminer:
            image: adminer
            ports: 
                - 8080:8080
        db:
            image: mysql:latest
            command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
            volumes: 
                - ./init-sql:/docker-entrypoint-initdb.d
            environment:
                MYSQL_ROOT_PASSWORD: kbot
        php:
            build: php-apache-mysqli
            ports:
                - 8888:80
            volumes:
                - ./html:/var/www/html/