version: '3.6'
services:
        db:
            image: mysql
            command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
            volumes: 
                - ./init-sql:/docker-entrypoint-initdb.d
                # - ./mysql-db:/var/lib/mysql
            environment:
                MYSQL_ROOT_PASSWORD: it635
        php:
            build: php-apache-mysqli
            ports:
                - 8888:80
            volumes:
                - ./html:/var/www/html/
        adminer:
            image: adminer
            ports: 
                - 8080:8080
        python: 
            build: py
            ports:
                - 5000:5000
            volumes: 
                - ./py:/py
        mailhog:
            image: mailhog/mailhog:v1.0.0
            ports:
                - "1025:1025"
                - "8025:8025"
        cron_simulate:
            build: cron

        